-- ============================================================
-- SEED: Áreas Protegidas de Chile (SNASPE - CONAF)
-- Parques Nacionales, Reservas Nacionales y Monumentos Naturales
-- ============================================================

-- Inserción con ON CONFLICT para poder re-ejecutar sin errores
INSERT INTO protected_areas (name, slug, type, region_name, area_ha, centroid, conaf_url, description)
VALUES

-- ── PARQUES NACIONALES ─────────────────────────────────────

('Torres del Paine',
 'torres-del-paine',
 'parque_nacional',
 'Magallanes y la Antártica Chilena',
 181414,
 ST_SetSRID(ST_MakePoint(-72.9333, -51.0667), 4326),
 'https://www.conaf.cl/parques/parque-nacional-torres-del-paine/',
 'Declarado Reserva de la Biosfera por la UNESCO, es uno de los parques más espectaculares del mundo. Alberga las icónicas torres de granito, glaciares y una rica biodiversidad patagónica.'),

('Conguillío',
 'conguillio',
 'parque_nacional',
 'La Araucanía',
 60832,
 ST_SetSRID(ST_MakePoint(-71.6333, -38.6833), 4326),
 'https://www.conaf.cl/parques/parque-nacional-conguillio/',
 'Hogar del volcán Llaima y extensos bosques de araucaria. La espectacular combinación de volcanes activos, lagunas y bosque de araucarias lo convierte en un destino único.'),

('Lauca',
 'lauca',
 'parque_nacional',
 'Arica y Parinacota',
 137883,
 ST_SetSRID(ST_MakePoint(-69.2667, -18.2167), 4326),
 'https://www.conaf.cl/parques/parque-nacional-lauca/',
 'Altiplano chileno con volcanes nevados, bofedales y la Laguna Chungará. Reserva de la Biosfera, hogar de vicuñas, flamencos y otras especies altiplánicas.'),

('Pan de Azúcar',
 'pan-de-azucar',
 'parque_nacional',
 'Atacama',
 43754,
 ST_SetSRID(ST_MakePoint(-70.6667, -26.1500), 4326),
 'https://www.conaf.cl/parques/parque-nacional-pan-de-azucar/',
 'Ecosistema desértico costero con abundante fauna marina. La isla Pan de Azúcar alberga una importante colonia de pingüinos de Humboldt, lobos marinos y aves guaneras.'),

('Bosque Fray Jorge',
 'bosque-fray-jorge',
 'parque_nacional',
 'Coquimbo',
 9959,
 ST_SetSRID(ST_MakePoint(-71.6500, -30.6500), 4326),
 'https://www.conaf.cl/parques/parque-nacional-bosque-fray-jorge/',
 'Relicto de bosque valdiviano en plena zona semiárida, mantenido por las camanchacas costeras. Reserva de la Biosfera y testimonio vivo de los cambios climáticos de Chile.'),

('La Campana',
 'la-campana',
 'parque_nacional',
 'Valparaíso',
 8000,
 ST_SetSRID(ST_MakePoint(-71.0667, -32.9500), 4326),
 'https://www.conaf.cl/parques/parque-nacional-la-campana/',
 'Reserva de la Biosfera con el bosque de palma chilena más importante del mundo. Fue visitado por Charles Darwin en 1834 y alberga más de 1.200 especies de flora.'),

('Radal 7 Tazas',
 'radal-7-tazas',
 'parque_nacional',
 'Maule',
 5148,
 ST_SetSRID(ST_MakePoint(-70.9833, -35.4833), 4326),
 'https://www.conaf.cl/parques/parque-nacional-radal-siete-tazas/',
 'Famoso por sus siete pozones naturales formados por el río Claro y sus cascadas. El bosque esclerófilo y el peumo caracterizan este parque de la zona central.'),

('Villarrica',
 'villarrica',
 'parque_nacional',
 'La Araucanía',
 61000,
 ST_SetSRID(ST_MakePoint(-71.9667, -39.4167), 4326),
 'https://www.conaf.cl/parques/parque-nacional-villarrica/',
 'Dominado por el volcán Villarrica, uno de los más activos de Sudamérica. Sus laderas están cubiertas de bosque valdiviano con araucarias, coihues y lengas.'),

('Puyehue',
 'puyehue',
 'parque_nacional',
 'Los Lagos',
 107000,
 ST_SetSRID(ST_MakePoint(-72.1000, -40.6667), 4326),
 'https://www.conaf.cl/parques/parque-nacional-puyehue/',
 'Incluye el volcán Puyehue y el Cordón Caulle. Sus termas, bosques húmedos y el lago Puyehue forman un ecosistema de gran biodiversidad en el sur de Chile.'),

('Vicente Pérez Rosales',
 'vicente-perez-rosales',
 'parque_nacional',
 'Los Lagos',
 251320,
 ST_SetSRID(ST_MakePoint(-72.1500, -41.0833), 4326),
 'https://www.conaf.cl/parques/parque-nacional-vicente-perez-rosales/',
 'El parque nacional más antiguo de Chile (1926). El volcán Osorno, el lago Todos los Santos y las cascadas Petrohué son sus íconos. Parte de la Reserva de la Biosfera Selva Valdiviana.'),

('Chiloé',
 'chiloe',
 'parque_nacional',
 'Los Lagos',
 43057,
 ST_SetSRID(ST_MakePoint(-74.0833, -42.6167), 4326),
 'https://www.conaf.cl/parques/parque-nacional-chiloe/',
 'Único parque que protege la selva valdiviana isleña. Es hábitat del pudú, el venado de los bosques, nutria marina y el ranita de Darwin. Importantes playas y humedales costeros.'),

('Laguna San Rafael',
 'laguna-san-rafael',
 'parque_nacional',
 'Aysén del General Carlos Ibáñez del Campo',
 1742000,
 ST_SetSRID(ST_MakePoint(-72.9167, -46.6333), 4326),
 'https://www.conaf.cl/parques/parque-nacional-laguna-san-rafael/',
 'Hogar del glaciar San Rafael, que termina en la laguna del mismo nombre. Es el parque más grande de Chile y uno de los ecosistemas de hielo más espectaculares del hemisferio sur.'),

('Bernardo O''Higgins',
 'bernardo-ohiggins',
 'parque_nacional',
 'Magallanes y la Antártica Chilena',
 3525901,
 ST_SetSRID(ST_MakePoint(-75.0000, -49.0000), 4326),
 'https://www.conaf.cl/parques/parque-nacional-bernardo-ohiggins/',
 'El parque nacional más extenso de Chile y uno de los más grandes del mundo. Cubre gran parte del Campo de Hielo Sur y es prácticamente inaccesible, preservando ecosistemas prístinos.'),

('Cabo de Hornos',
 'cabo-de-hornos',
 'parque_nacional',
 'Magallanes y la Antártica Chilena',
 4880000,
 ST_SetSRID(ST_MakePoint(-67.5000, -55.5000), 4326),
 'https://www.conaf.cl/parques/parque-nacional-cabo-de-hornos/',
 'El parque más austral del mundo, incluye el famoso Cabo de Hornos. Reserva de la Biosfera de la UNESCO, alberga turberas, bosque subantártico y es hogar del cóndor andino.'),

('Nahuelbuta',
 'nahuelbuta',
 'parque_nacional',
 'La Araucanía',
 6832,
 ST_SetSRID(ST_MakePoint(-73.0167, -37.8000), 4326),
 'https://www.conaf.cl/parques/parque-nacional-nahuelbuta/',
 'Último reducto de araucarias en la Cordillera de Nahuelbuta. Sus imponentes ejemplares milenarios coexisten con el bosque valdiviano, hogar del monito del monte y el puma.'),

('Pampa del Tamarugal',
 'pampa-del-tamarugal',
 'parque_nacional',
 'Tarapacá',
 100650,
 ST_SetSRID(ST_MakePoint(-69.6667, -20.5000), 4326),
 'https://www.conaf.cl/parques/parque-nacional-pampa-del-tamarugal/',
 'Extenso bosque de tamarugos en pleno desierto de Atacama. Esta especie arbórea única extrae agua del subsuelo permitiendo la vida en uno de los desiertos más áridos del mundo.'),

('Llanos de Challe',
 'llanos-de-challe',
 'parque_nacional',
 'Atacama',
 45708,
 ST_SetSRID(ST_MakePoint(-71.0833, -28.1167), 4326),
 'https://www.conaf.cl/parques/parque-nacional-llanos-de-challe/',
 'Famoso por el fenómeno del desierto florido en años de El Niño. Cactáceas, flora endémica del desierto costero y el gato de Geoffroy son algunas de sus especies más representativas.'),

('Nevado Tres Cruces',
 'nevado-tres-cruces',
 'parque_nacional',
 'Atacama',
 59082,
 ST_SetSRID(ST_MakePoint(-68.8167, -27.1000), 4326),
 'https://www.conaf.cl/parques/parque-nacional-nevado-tres-cruces/',
 'Laguna Santa Rosa y Laguna del Negro Francisco en el altiplano atacameño. Hábitat crítico para flamencos, vicuñas y la más alta biodiversidad del desierto de altura.'),

('Isla Mocha',
 'isla-mocha',
 'parque_nacional',
 'Biobío',
 2625,
 ST_SetSRID(ST_MakePoint(-73.9167, -38.3500), 4326),
 'https://www.conaf.cl/parques/parque-nacional-isla-mocha/',
 'Isla ubicada frente a las costas de Arauco, con bosque templado costero. Importante sitio de avifauna, con numerosas aves migratorias y residentes en sus playas y bosques.'),

('Juan Fernández',
 'juan-fernandez',
 'parque_nacional',
 'Valparaíso',
 9292,
 ST_SetSRID(ST_MakePoint(-78.8333, -33.6167), 4326),
 'https://www.conaf.cl/parques/parque-nacional-juan-fernandez/',
 'Archipiélago oceánico con altísimo endemismo. El 62% de su flora es endémica. Reserva de la Biosfera y hábitat del lobo fino de Juan Fernández, el picaflor de Juan Fernández y múltiples especies únicas.'),

('Rapa Nui',
 'rapa-nui',
 'parque_nacional',
 'Valparaíso',
 7130,
 ST_SetSRID(ST_MakePoint(-109.3667, -27.1167), 4326),
 'https://www.conaf.cl/parques/parque-nacional-rapa-nui/',
 'Patrimonio de la Humanidad UNESCO que cubre gran parte de la Isla de Pascua. Sus moáis y ceremonias culturales conviven con ecosistemas marinos y costeros únicos del Pacífico.'),

('Huerquehue',
 'huerquehue',
 'parque_nacional',
 'La Araucanía',
 12500,
 ST_SetSRID(ST_MakePoint(-71.7667, -39.1833), 4326),
 'https://www.conaf.cl/parques/parque-nacional-huerquehue/',
 'Lagunas cristalinas rodeadas de araucarias milenarias y coihues. Forma parte de la cuenca del lago Caburgua y es conocido por sus espectaculares paisajes lacustres.'),

('Queulat',
 'queulat',
 'parque_nacional',
 'Aysén del General Carlos Ibáñez del Campo',
 154093,
 ST_SetSRID(ST_MakePoint(-72.6833, -44.3667), 4326),
 'https://www.conaf.cl/parques/parque-nacional-queulat/',
 'Ventisquero Colgante y selva valdiviana húmeda son sus principales atractivos. Sus bosques con abundantes epífitas, helechos arbóreos y el alerce lo convierten en un ecosistema único.'),

('Los Glaciares del Sur',
 'alerce-andino',
 'parque_nacional',
 'Los Lagos',
 39255,
 ST_SetSRID(ST_MakePoint(-72.5500, -41.7500), 4326),
 'https://www.conaf.cl/parques/parque-nacional-alerce-andino/',
 'Bosques de alerce milenario en la cordillera patagónica. Algunos ejemplares superan los 3.000 años, convirtiéndolos en los seres vivos más antiguos de Chile.'),

-- ── RESERVAS NACIONALES ────────────────────────────────────

('Las Chinchillas',
 'las-chinchillas',
 'reserva_nacional',
 'Coquimbo',
 4229,
 ST_SetSRID(ST_MakePoint(-71.1000, -31.5000), 4326),
 'https://www.conaf.cl/parques/reserva-nacional-las-chinchillas/',
 'Único lugar en Chile que protege poblaciones silvestres de chinchilla de cola corta. Parte de los esfuerzos de conservación de esta especie criticamente amenazada.'),

('Lago Peñuelas',
 'lago-penuelas',
 'reserva_nacional',
 'Valparaíso',
 9260,
 ST_SetSRID(ST_MakePoint(-71.5333, -33.1667), 4326),
 'https://www.conaf.cl/parques/reserva-nacional-lago-penuelas/',
 'Reserva hídrica y Reserva de la Biosfera que abastece de agua a Valparaíso. Su lago y bosque esclerófilo son hábitat de más de 100 especies de aves.'),

('Malleco',
 'malleco',
 'reserva_nacional',
 'La Araucanía',
 16625,
 ST_SetSRID(ST_MakePoint(-71.8833, -38.0167), 4326),
 'https://www.conaf.cl/parques/reserva-nacional-malleco/',
 'Primera área protegida de Chile, creada en 1907. Sus bosques nativos de roble, raulí y coihue son fundamentales para la cuenca del río Malleco.'),

('Coyhaique',
 'coyhaique',
 'reserva_nacional',
 'Aysén del General Carlos Ibáñez del Campo',
 2150,
 ST_SetSRID(ST_MakePoint(-72.0667, -45.5833), 4326),
 'https://www.conaf.cl/parques/reserva-nacional-coyhaique/',
 'Reserva forestal cercana a la capital regional de Aysén. Sus bosques de lenga y ñirre son utilizados para educación ambiental y ecoturismo por la comunidad local.'),

('Río Simpson',
 'rio-simpson',
 'reserva_nacional',
 'Aysén del General Carlos Ibáñez del Campo',
 41621,
 ST_SetSRID(ST_MakePoint(-72.5000, -45.7667), 4326),
 'https://www.conaf.cl/parques/reserva-nacional-rio-simpson/',
 'Selva valdiviana con abundante vegetación húmeda y el río Simpson. Sus bosques albergan huemul, pudú y múltiples especies de aves autóctonas del sur de Chile.'),

('Mañihuales',
 'manihuales',
 'reserva_nacional',
 'Aysén del General Carlos Ibáñez del Campo',
 25790,
 ST_SetSRID(ST_MakePoint(-72.4333, -45.1833), 4326),
 'https://www.conaf.cl/parques/reserva-nacional-manihuales/',
 'Bosques de cipres de la cordillera y lenga en el corazón de Aysén. Importante área de protección de la cuenca hidrográfica de la región.'),

('Katalalixar',
 'katalalixar',
 'reserva_nacional',
 'Aysén del General Carlos Ibáñez del Campo',
 674600,
 ST_SetSRID(ST_MakePoint(-74.5000, -48.2500), 4326),
 'https://www.conaf.cl/parques/reserva-nacional-katalalixar/',
 'Canales patagónicos con islas, fiordos y bosques subantárticos. Área de gran valor para la conservación de ecosistemas marinos y costeros del extremo austral.'),

('Las Vicuñas',
 'las-vicunas',
 'reserva_nacional',
 'Arica y Parinacota',
 209131,
 ST_SetSRID(ST_MakePoint(-69.5000, -18.7000), 4326),
 'https://www.conaf.cl/parques/reserva-nacional-las-vicunas/',
 'Extensa reserva altiplánica que protege las mayores poblaciones de vicuña del país. Bofedales y volcanes nevados caracterizan este paisaje de alta montaña.'),

('Pampa Galeras',
 'alto-loa',
 'reserva_nacional',
 'Antofagasta',
 201534,
 ST_SetSRID(ST_MakePoint(-68.5000, -22.5000), 4326),
 'https://www.conaf.cl/parques/reserva-nacional-alto-loa/',
 'Parte del altiplano atacameño con lagunas altoandinas y bofedales. Importante para la conservación del flamenco andino, la vicuña y el guanaco.'),

('Valparaíso',
 'reserva-valparaiso',
 'reserva_nacional',
 'Valparaíso',
 17096,
 ST_SetSRID(ST_MakePoint(-71.4167, -33.0667), 4326),
 'https://www.conaf.cl/parques/reserva-nacional-valparaiso/',
 'Bosque esclerófilo y matorral mediterráneo en los cerros de la región. Protege cuencas hidrográficas importantes y ofrece áreas de recreación para la población de la región.'),

-- ── MONUMENTOS NATURALES ───────────────────────────────────

('La Portada',
 'la-portada',
 'monumento_natural',
 'Antofagasta',
 31,
 ST_SetSRID(ST_MakePoint(-70.3500, -23.6333), 4326),
 'https://www.conaf.cl/parques/monumento-natural-la-portada/',
 'Imponente arco de roca natural formado por la erosión marina. Santuario para aves marinas como el guanay, la garza, y las algas marinas en un ecosistema costero único.'),

('Los Pinguinos',
 'los-pinguinos',
 'monumento_natural',
 'Magallanes y la Antártica Chilena',
 97,
 ST_SetSRID(ST_MakePoint(-70.9167, -52.5333), 4326),
 'https://www.conaf.cl/parques/monumento-natural-los-pinguinos/',
 'Isla Magdalena alberga una de las mayores colonias de pingüino de Magallanes. Aproximadamente 60.000 parejas nidifican aquí cada temporada reproductiva.'),

('Pichasca',
 'pichasca',
 'monumento_natural',
 'Coquimbo',
 128,
 ST_SetSRID(ST_MakePoint(-70.8167, -30.5667), 4326),
 'https://www.conaf.cl/parques/monumento-natural-pichasca/',
 'Sitio paleontológico con fósiles de dinosaurios y árboles petrificados del Cretácico. Los troncos silicificados de más de 65 millones de años son su principal atractivo.'),

('El Morado',
 'el-morado',
 'monumento_natural',
 'Metropolitana de Santiago',
 3009,
 ST_SetSRID(ST_MakePoint(-70.0833, -33.7667), 4326),
 'https://www.conaf.cl/parques/monumento-natural-el-morado/',
 'Glaciar San Francisco y laguna El Morado en los Andes de Santiago. Accesible desde la capital, ofrece ecosistemas de alta montaña con flora y fauna andina.'),

('Contulmo',
 'contulmo',
 'monumento_natural',
 'Biobío',
 82,
 ST_SetSRID(ST_MakePoint(-73.2333, -38.0000), 4326),
 'https://www.conaf.cl/parques/monumento-natural-contulmo/',
 'Pequeño pero valioso relicto de bosque valdiviano en la Cordillera de Nahuelbuta. Sus árboles centenarios incluyen ulmos, tilos y canelos de gran porte.'),

('Cueva del Milodón',
 'cueva-del-milodon',
 'monumento_natural',
 'Magallanes y la Antártica Chilena',
 189,
 ST_SetSRID(ST_MakePoint(-72.6000, -51.5833), 4326),
 'https://www.conaf.cl/parques/monumento-natural-cueva-del-milodon/',
 'Cueva prehistórica donde se encontraron restos del milodón, un mamífero parecido al perezoso que vivió hace 10.000 años. Patrimonio paleontológico y cultural de la Patagonia.'),

('Dos Lagunas',
 'dos-lagunas',
 'monumento_natural',
 'Aysén del General Carlos Ibáñez del Campo',
 181,
 ST_SetSRID(ST_MakePoint(-72.2500, -45.5833), 4326),
 'https://www.conaf.cl/parques/monumento-natural-dos-lagunas/',
 'Dos lagunas de origen volcánico en el valle de Coyhaique. Sus aguas cristalinas y el bosque circundante de lenga y coihue son el principal atractivo de esta pequeña área.'),

('Cerro Ñielol',
 'cerro-nielol',
 'monumento_natural',
 'La Araucanía',
 89,
 ST_SetSRID(ST_MakePoint(-72.6167, -38.7333), 4326),
 'https://www.conaf.cl/parques/monumento-natural-cerro-nielol/',
 'Cerro sagrado para el pueblo mapuche, ubicado en el corazón de Temuco. Bosque nativo templado con canelos, coihues y ulmos, además de gran valor cultural e histórico.'),

('Isla Cachagua',
 'isla-cachagua',
 'monumento_natural',
 'Valparaíso',
 5,
 ST_SetSRID(ST_MakePoint(-71.4833, -32.5833), 4326),
 'https://www.conaf.cl/parques/monumento-natural-isla-cachagua/',
 'Pequeña isla frente a Zapallar, santuario para la colonia de pingüinos de Humboldt. También es hábitat de lobos marinos y numerosas aves marinas de la costa central.')

ON CONFLICT (slug) DO UPDATE SET
  name        = EXCLUDED.name,
  type        = EXCLUDED.type,
  region_name = EXCLUDED.region_name,
  area_ha     = EXCLUDED.area_ha,
  centroid    = EXCLUDED.centroid,
  conaf_url   = EXCLUDED.conaf_url,
  description = EXCLUDED.description;
